import { Task, TaskAIAnalysis, FocusCoachResponse } from '../../types';

export const getMockUrgencyAnalysis = (task: Task): TaskAIAnalysis => {
  const currentHoursRemaining = Math.max(0, (new Date(task.deadline).getTime() - Date.now()) / (1000 * 60 * 60));
  let calculatedScore = Math.round(task.urgencyScore || 50);

  // Fallback reasoning based on parameters
  let reasoning = `Analysis executed on task "${task.title}". `;
  let blockers: string[] = [];
  let nextAction = '';

  if (task.priority === 'high' || calculatedScore > 70) {
    reasoning += `This task represents a critical block in your workflow. The deadline is fast approaching (${Math.round(currentHoursRemaining)} hours remaining), and the impact level of ${task.impact}/5 indicates severe operational risk if missed. Immediate action is heavily recommended to avoid a downstream bottleneck.`;
    blockers = task.dependencies.length > 0 
      ? [`Blocked by task dependencies: ${task.dependencies.join(', ')}`] 
      : ['Awaiting final design specs', 'Local environment configuration issues'];
    nextAction = `Isolate the first module, turn off notifications, and spend exactly 15 minutes drafting the core architectural draft.`;
  } else if (task.priority === 'medium' || (calculatedScore > 40 && calculatedScore <= 70)) {
    reasoning += `This is a moderate priority task. While the deadline allows for comfortable planning (~${Math.round(currentHoursRemaining / 24)} days left), its impact score (${task.impact}/5) demands steady incremental progress to prevent it from compounding into high urgency later this week.`;
    blockers = ['Awaiting feedback from peer review'];
    nextAction = `Set up a clean code sandbox and implement the interface skeleton using placeholder items.`;
  } else {
    reasoning += `This task is currently stable. With a low impact rating and plenty of buffer time before the deadline, you can safely schedule this for low-energy blocks or delegate it if necessary. Keep track of progress but do not let it distract you from high-impact work.`;
    blockers = ['None'];
    nextAction = `Review the task description and add bullet-point notes of any potential scope items.`;
  }

  return {
    urgency_score: calculatedScore,
    reasoning,
    blockers,
    next_action: nextAction,
    analyzedAt: new Date().toISOString()
  };
};

export const getMockBulkParsedTasks = (rawText: string): any[] => {
  const lowercase = rawText.toLowerCase();
  const parsed: any[] = [];

  if (lowercase.includes('report') || lowercase.includes('meeting') || lowercase.includes('slide')) {
    parsed.push({
      title: 'Synthesize quarterly engineering report',
      description: 'Review commit histories, sprint velocities, and database optimization logs. Format into high-level summary cards.',
      deadline: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      category: 'Work',
      priority: 'high',
      impact: 4
    });
    parsed.push({
      title: 'Schedule alignment call with UX lead',
      description: 'Discuss the design-to-development handoff for the dark glassmorphism system components.',
      deadline: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
      category: 'Work',
      priority: 'medium',
      impact: 3
    });
  }

  if (lowercase.includes('buy') || lowercase.includes('shop') || lowercase.includes('grocery')) {
    parsed.push({
      title: 'Restock development fuel & nutritional supplies',
      description: 'Pick up dark roast espresso beans, complex carb snacks, and electrolyte hydration tablets.',
      deadline: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
      category: 'Life',
      priority: 'low',
      impact: 2
    });
  }

  // Fallback if no keywords matched
  if (parsed.length === 0) {
    parsed.push({
      title: rawText.substring(0, 40) + (rawText.length > 40 ? '...' : ''),
      description: `Inferred from brain-dump: "${rawText}"`,
      deadline: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
      category: 'General',
      priority: 'medium',
      impact: 3
    });
  }

  return parsed;
};

export const getMockWeeklyPlan = (tasks: Task[]): string => {
  const activeTasks = tasks.filter(t => t.status !== 'done');
  
  return `
# 📅 STRATEGIC ACTION PLAN: WEEKLY CALENDAR

Generated by **LIFELINE AI Pro Engine**. Focused on reducing cognitive friction and securing critical milestones.

---

## 📊 Strategic Summary
- **Master Backlog Size**: ${tasks.length} tasks
- **Active Focus Load**: ${activeTasks.length} tasks
- **Primary Danger Zone**: ${activeTasks.filter(t => t.urgencyScore > 70).length} tasks flashing extreme urgency score (>70).

---

## 🗓 Day-by-Day Focus Schedule

### **Monday: Critical Velocity & Inception**
*Theme: Execute the highest-friction bottlenecks first.*
* **09:00 - 11:30** | **DEEP WORK BLOCK**: [CRITICAL] Prepare presentation slides
  * *Notes*: Deadline in 4 hours. No notifications. Focus entirely on layout & value propositions.
* **13:00 - 14:30** | **ENGINEERING EXECUTION**: Review production database security rules
  * *Notes*: Ensure firebase rules are strict.
* **15:00 - 16:30** | **COLLABORATIVE SYNC**: Clear dependencies and message blocked team members.

### **Tuesday: Structural Resilience**
*Theme: Build core infrastructure and secure the perimeter.*
* **09:30 - 12:00** | **REFACTOR BLOCK**: Refactor state manager & optimize rerenders
  * *Notes*: High-priority engineering work. This clears UI latency for the user dashboard.
* **14:00 - 15:30** | **ADMIN & TRIAGE**: Catch-up on general team requests and email communications.

### **Wednesday: Quality Assurance & Hardening**
*Theme: Build tests and secure operational integrity.*
* **10:00 - 12:30** | **DEEP TESTING BLOCK**: Write automated unit tests for Lifeline Score
  * *Notes*: Coverage must exceed 90% for core algorithms. Focus on edge cases.
* **14:00 - 16:00** | **PERFORMANCE SHAPING**: Analyze logs, optimize db indices, and profile memory leaks.

### **Thursday: Polish & Deployment**
*Theme: Refine presentation layer and publish assets.*
* **09:00 - 12:00** | **REVIEWS & REFINEMENT**: Clean up UI layouts and test responsiveness down to 320px.
* **13:30 - 15:00** | **DEPLOYMENT READY**: Deploy database schema to staging.

### **Friday: Reflection & Buffer**
*Theme: Retrospective analysis & backlog grooming.*
* **10:00 - 12:00** | **STRATEGIC REVIEW**: Assess weekly completion statistics. Update user streak records.
* **14:00 - 15:30** | **DE-CLUTTER WINDOW**: Tackle light tasks, organize folders, archive completed epics.

---

## 🎯 Tactical Directives from Coach Pro:
1. **Eat the Frog**: The slide deck must ship first thing Monday. Everything else flows around it.
2. **Respect Dependencies**: Do not touch the Refactoring block until you complete the security review on Monday.
3. **Recovery Buffer**: You have 12 hours of unallocated time. Use it to recover from unexpected fires.
`;
};

export const getMockFocusCoaching = (task: Task): FocusCoachResponse => {
  return {
    subtasks: [
      { title: 'De-clutter workspace & isolate focus browser tab', durationMinutes: 5 },
      { title: 'Spend 10 minutes drafting the raw outline on scratchpad', durationMinutes: 10 },
      { title: 'Build the single core component interface layout', durationMinutes: 10 }
    ],
    coachingMessage: `Listen up, Creator. Procrastination is just a fear of starting. The calculated Lifeline Score™ for "${task.title}" is a pulsing ${task.urgencyScore}/100! That is your signal to execute. We are not doing the whole task right now — we are just doing the first 5 minutes. Put on your headphones, start the Pomodoro timer, and let's claim this victory. You have the skills. Go!`
  };
};
